# Portada de la parte de administración
backend_portada:
    pattern:  /
    defaults: { _controller: BackendBundle:Oferta:index }

# Ruta para el cambio de la ciudad activa en la parte de administación
backend_ciudad_cambiar:
    pattern:  /cambiar-a-{ciudad}
    defaults: { _controller: BackendBundle:Default:ciudadCambiar }
    requirements:
        ciudad: .+

# Importar las rutas de la entidad Ciudad generadas en el bundle BackendBundle
BackendCiudad:
    resource: "@BackendBundle/Resources/config/routing/ciudad.yml"
    prefix:   /ciudad

# Importar las rutas de la entidad Oferta generadas en el bundle BackendBundle
BackendOferta:
    resource: "@BackendBundle/Resources/config/routing/oferta.yml"
    prefix:   /oferta

# Importar las rutas de la entidad Tienda generadas en el bundle BackendBundle
BackendTienda:
    resource: "@BackendBundle/Resources/config/routing/tienda.yml"
    prefix:   /tienda

# Importar las rutas de la entidad Usuario generadas en el bundle BackendBundle
BackendUsuario:
    resource: "@BackendBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario
