imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Configuración general del framework
framework:
    default_locale:  %locale%
    esi:             { enabled: true }
    translator:      { fallback: es }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    trusted_hosts:   ~
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:         ~

# Configuración de Twig
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        ciudad_por_defecto:  %cupon.ciudad_por_defecto%
        directorio_imagenes: '/uploads/images/'

# Configuración de Assetic
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
#        yui_css:
#            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
#            apply_to: \.css$
#        yui_js:
#            jar:      %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
#            apply_to: \.js$

#        optipng:
#            bin: /usr/local/bin/optipng
#
#    twig:
#        functions:
#            optipng: ~

# Configuración de Doctrine
doctrine:
    dbal:
        driver:   %database_driver%
        charset:  UTF8
        # Si NO usas SQLite, comenta esta línea
        path:     "%database_path%"
        # Si usas MySQL, descomenta estas líneas
        # host:     %database_host%
        # port:     %database_port%
        # dbname:   %database_name%
        # user:     %database_user%
        # password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping:                true

# Configuración de Swiftmailer
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# Parámetros globales del contenedor de dependencias
parameters:
    cupon.ciudad_por_defecto:  'barcelona'
    cupon.directorio.imagenes: %kernel.root_dir%/../web/uploads/images/

# Descomenta las siguientes líneas para probar Sonata Admin Bundle
# sonata_admin:
#    title:      'Cupon - Backend'
#    title_logo: /bundles/backend/logotipo.png

# sonata_block:
#    default_contexts: [cms]
#    blocks:
#        sonata.admin.block.admin_list:
#            contexts:   [admin]

#        sonata.block.service.text:   ~
#        sonata.block.service.action: ~
#        sonata.block.service.rss:    ~

# services:
#     sonata.cupon.admin.oferta:
#         class: Cupon\OfertaBundle\Admin\OfertaAdmin
#         tags:
#             - { name: sonata.admin, manager_type: orm, group: 'Ofertas y Ventas', label: Ofertas }
#         arguments:
#             - null
#             - Cupon\OfertaBundle\Entity\Oferta
#             - OfertaBundle:Admin
