# Rutas de las páginas estáticas del sitio
ayuda:
    path: /ayuda
    defaults: { template: 'sitio/ayuda.html.twig' }

privacidad:
    path: /privacidad
    defaults: { template: 'sitio/privacidad.html.twig' }

sobre_nosotros:
    path: /sobre-nosotros
    defaults: { template: 'sitio/sobre_nosotros.html.twig' }
