_backend:
    resource: '@EasyAdminBundle/Controller/'
    type:     annotation
    prefix:   /admin

_paginas:
    resource: routing_paginas.yml
    prefix:   /{_locale}/sitio
    requirements:
        _locale: en|es
    defaults:
        _locale: '%locale%'
        _controller: FrameworkBundle:Template:template
        private: false
        maxAge: 86400
        sharedMaxAge: 86400

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: '%locale%'

_extranet:
    resource: '@AppBundle/Controller/ExtranetController.php'
    type:     annotation
    prefix:   /extranet

# Ruta de la portada básica del sitio (sin ningún parámetro)
# esta ruta es opcional, ya que la aplicación puede funcionar bien
# solamente con la ruta 'portada' y sus valores por defecto
_portada:
     path:  /
     defaults:
          _controller: FrameworkBundle:Redirect:redirect
          route: portada
          ciudad: '%app.ciudad_por_defecto%'
